# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'realmSandbox4ios' do
 pod 'RealmSwift' 
end

target 'realmSandbox4iosTests' do
 pod 'RealmSwift' 
end

