# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'leaderboard_ios' do
pod 'ObjectiveDDP'

end

target 'leaderboard_iosTests' do
pod 'ObjectiveDDP'

end

