# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
use_frameworks!

target 'rxSwiftStudy' do
pod 'RxSwift'
pod 'RxCocoa'
end

target 'rxSwiftStudyTests' do
pod 'RxSwift'
pod 'RxCocoa'
end

