# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'tryRealm' do
pod "Realm"
pod "ReactiveCocoa"
end

target 'tryRealmTests' do
pod "Realm/Headers"
pod "ReactiveCocoa"
end

