# Uncomment this line to define a global platform for your project
platform :osx, '10.10'
use_frameworks!

target 'realmSandbox' do
 pod 'RealmSwift' 
end

target 'realmSandboxTests' do
 pod 'RealmSwift' 
end

