# Uncomment this line to define a global platform for your project
platform :osx, '10.11'
# Uncomment this line if you're using Swift
use_frameworks!

target 'keyLogger' do
pod 'RealmSwift'
end

target 'keyLoggerTests' do
pod 'RealmSwift'
end

target 'keyLoggerUITests' do
pod 'RealmSwift'
end
